import 'package:firebase_database/firebase_database.dart';
import '../models/report.dart';
import 'base_service.dart';
import 'analytics_service.dart';
import 'player_service.dart';
import 'team_service.dart';
import 'match_service.dart';

class ReportService {
  final DatabaseReference _ref = dbRef.reports();

  Future<String> createReport(Report report) async {
    final newRef = _ref.push();
    await newRef.set(report.toMap());
    return newRef.key ?? '';
  }

  Future<List<Report>> getAllReports() async {
    final reports = <Report>[];
    try {
      final snapshot = await _ref.get();
      if (snapshot.exists) {
        for (var child in snapshot.children) {
          final data = Map<String, dynamic>.from(child.value as Map);
          reports.add(Report.fromMap(child.key ?? '', data));
        }
      }
    } catch (e) {
      print('Error getting all reports: $e');
    }
    return reports;
  }

  Future<List<Report>> getReportsByType(ReportType type) async {
    final reports = <Report>[];
    try {
      final snapshot = await _ref.orderByChild('type').equalTo(type.name).get();
      if (snapshot.exists) {
        for (var child in snapshot.children) {
          final data = Map<String, dynamic>.from(child.value as Map);
          reports.add(Report.fromMap(child.key ?? '', data));
        }
      }
    } catch (e) {
      print('Error getting reports by type: $e');
    }
    return reports;
  }

  Future<List<Report>> getReportsByPlayer(String playerId) async {
    final reports = <Report>[];
    try {
      final snapshot = await _ref
          .orderByChild('player_id')
          .equalTo(playerId)
          .get();
      if (snapshot.exists) {
        for (var child in snapshot.children) {
          final data = Map<String, dynamic>.from(child.value as Map);
          reports.add(Report.fromMap(child.key ?? '', data));
        }
      }
    } catch (e) {
      print('Error getting reports by player: $e');
    }
    return reports;
  }

  Future<List<Report>> getReportsByTeam(String teamId) async {
    final reports = <Report>[];
    try {
      final snapshot = await _ref.orderByChild('team_id').equalTo(teamId).get();
      if (snapshot.exists) {
        for (var child in snapshot.children) {
          final data = Map<String, dynamic>.from(child.value as Map);
          reports.add(Report.fromMap(child.key ?? '', data));
        }
      }
    } catch (e) {
      print('Error getting reports by team: $e');
    }
    return reports;
  }

  Future<void> deleteReport(String reportId) async {
    await _ref.child(reportId).remove();
  }

  Future<String> generatePlayerProgressReport({
    required String playerId,
    required String playerName,
    required String generatedBy,
  }) async {
    final analyticsService = AnalyticsService();
    final playerService = PlayerServiceImpl();

    final player = await playerService.getPlayer(playerId);
    final stats = await analyticsService.getPlayerStats(playerId);
    final attendance = await analyticsService.getPlayerAttendanceRate(playerId);

    final goals = stats['goals'] ?? 0;
    final assists = stats['assists'] ?? 0;
    final avgRating = stats['avgRating'] ?? 0.0;
    final totalMatches = stats['totalMatches'] ?? 0;

    String content =
        '''
Player: $playerName
Position: ${player?.position ?? 'N/A'}
Date: ${DateTime.now().toString().split(' ')[0]}

=== PERFORMANCE SUMMARY ===

Total Matches Played: $totalMatches
Goals: $goals
Assists: $assists
Total Goal Contributions: ${goals + assists}
Average Rating: ${avgRating.toStringAsFixed(1)}/10

=== ATTENDANCE ===

Training Attendance: ${attendance.toStringAsFixed(1)}%

=== OVERALL ASSESSMENT ===

${_getPerformanceAssessment(avgRating, attendance)}

Generated by: $generatedBy
''';

    final report = Report(
      type: ReportType.playerProgress,
      title: 'Player Progress Report - $playerName',
      content: content,
      playerId: playerId,
      generatedBy: generatedBy,
    );

    return createReport(report);
  }

  Future<String> generateTeamPerformanceReport({
    required String teamId,
    required String teamName,
    required String generatedBy,
  }) async {
    final analyticsService = AnalyticsService();
    final matchService = MatchServiceImpl();

    final stats = await analyticsService.getTeamStats(teamId);
    final matches = await matchService.getMatchesByTeam(teamId);

    final wins = stats['wins'] ?? 0;
    final losses = stats['losses'] ?? 0;
    final draws = stats['draws'] ?? 0;
    final goalsScored = stats['goalsScored'] ?? 0;
    final goalsConceded = stats['goalsConceded'] ?? 0;
    final totalMatches = stats['totalMatches'] ?? 0;

    final winRate = totalMatches > 0 ? (wins / totalMatches * 100) : 0.0;
    final goalDiff = goalsScored - goalsConceded;

    String content =
        '''
Team: $teamName
Date: ${DateTime.now().toString().split(' ')[0]}

=== MATCH SUMMARY ===

Total Matches: $totalMatches
Wins: $wins
Draws: $draws
Losses: $losses
Win Rate: ${winRate.toStringAsFixed(1)}%

=== GOAL STATISTICS ===

Goals Scored: $goalsScored
Goals Conceded: $goalsConceded
Goal Difference: ${goalDiff >= 0 ? '+$goalDiff' : '$goalDiff'}
Average Goals per Match: ${totalMatches > 0 ? (goalsScored / totalMatches).toStringAsFixed(1) : '0'}

=== OVERALL ASSESSMENT ===

${_getTeamAssessment(winRate, goalDiff)}

Generated by: $generatedBy
''';

    final report = Report(
      type: ReportType.teamPerformance,
      title: 'Team Performance Report - $teamName',
      content: content,
      teamId: teamId,
      generatedBy: generatedBy,
    );

    return createReport(report);
  }

  Future<String> generateFinancialSummaryReport({
    required String generatedBy,
  }) async {
    final analyticsService = AnalyticsService();

    final totalRevenue = await analyticsService.getTotalRevenue();
    final pendingCount = await analyticsService.getPendingPaymentsCount();
    final monthlyTrend = await analyticsService.getMonthlyTrend(
      DateTime.now().year,
    );

    double monthlyIncome = 0;
    for (var entry in monthlyTrend.entries) {
      monthlyIncome += entry.value;
    }

    String content =
        '''
Real Galaxy Academy - Financial Summary
Date: ${DateTime.now().toString().split(' ')[0]}

=== OVERVIEW ===

Total Revenue (All Time): ₵${totalRevenue.toStringAsFixed(2)}
Pending Payments: $pendingCount

=== MONTHLY BREAKDOWN ===

''';

    final months = [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ];
    for (int i = 0; i < 12; i++) {
      final month = i + 1;
      final amount = monthlyTrend['$month'] ?? 0;
      content += '${months[i]}: ₵${amount.toStringAsFixed(2)}\n';
    }

    content +=
        '''
=== SUMMARY ===

Total Income This Year: ₵${monthlyIncome.toStringAsFixed(2)}
${pendingCount > 0 ? 'Action required: $pendingCount pending payment(s)' : 'All payments up to date'}

Generated by: $generatedBy
''';

    final report = Report(
      type: ReportType.financialSummary,
      title: 'Financial Summary Report',
      content: content,
      generatedBy: generatedBy,
    );

    return createReport(report);
  }

  Future<String> generateMonthlyAcademyReport({
    required String generatedBy,
  }) async {
    final analyticsService = AnalyticsService();
    final playerService = PlayerServiceImpl();
    final teamService = TeamServiceImplementation();
    final matchService = MatchServiceImpl();

    final overview = await analyticsService.getAcademyOverview();
    final players = await playerService.getAllPlayers();
    final teams = await teamService.getAllTeams();
    final matches = await matchService.getAllMatches();
    final totalRevenue = await analyticsService.getTotalRevenue();

    final totalPlayers = overview['totalPlayers'] ?? 0;
    final totalTeams = overview['totalTeams'] ?? 0;
    final pendingPayments = overview['pendingPayments'] ?? 0;

    final currentMonth = DateTime.now().month;
    final currentYear = DateTime.now().year;
    final monthlyRevenue = await analyticsService.getMonthlyRevenue(
      currentYear,
      currentMonth,
    );

    String content =
        '''
Real Galaxy Academy - Monthly Report
Month: ${_getMonthName(currentMonth)} $currentYear
Generated: ${DateTime.now().toString().split(' ')[0]}

=== ACADEMY OVERVIEW ===

Total Players: $totalPlayers
Total Teams: $totalTeams
Total Matches Played: ${matches.length}
Total Revenue: ₵${totalRevenue.toStringAsFixed(2)}

=== THIS MONTH ===

Revenue: ₵${monthlyRevenue.toStringAsFixed(2)}
Pending Payments: $pendingPayments

=== TEAMS SUMMARY ===

${teams.map((t) => '${t.name}: ${t.playersCount} players').join('\n')}

Generated by: $generatedBy
''';

    final report = Report(
      type: ReportType.monthlyAcademy,
      title:
          'Monthly Academy Report - ${_getMonthName(currentMonth)} $currentYear',
      content: content,
      generatedBy: generatedBy,
    );

    return createReport(report);
  }

  String _getPerformanceAssessment(double avgRating, double attendance) {
    if (avgRating >= 8 && attendance >= 90) {
      return 'Excellent performer with outstanding attendance. Ready for advanced training.';
    } else if (avgRating >= 7 && attendance >= 80) {
      return 'Good performance and consistent attendance. Keep up the good work.';
    } else if (avgRating >= 6 && attendance >= 70) {
      return 'Satisfactory performance. Encourage more participation in training.';
    } else if (avgRating >= 5 && attendance >= 60) {
      return 'Needs improvement in both performance and attendance.';
    } else {
      return 'Requires attention. Consider additional support and motivation.';
    }
  }

  String _getTeamAssessment(double winRate, int goalDiff) {
    if (winRate >= 70 && goalDiff > 0) {
      return 'Excellent team performance. Strong attacking and solid defense.';
    } else if (winRate >= 50 && goalDiff >= 0) {
      return 'Good team performance. Continue building on strengths.';
    } else if (winRate >= 40) {
      return 'Moderate performance. Focus on defensive improvements.';
    } else {
      return 'Needs improvement. Review tactics and team coordination.';
    }
  }

  String _getMonthName(int month) {
    const months = [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July',
      'August',
      'September',
      'October',
      'November',
      'December',
    ];
    return months[month - 1];
  }
}

